name: first jobs

on: workflow_dispatch

env:
  NAME: Avnesh

jobs:
  my_first_job:
    name: my_first job
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v6.0.2
       
     - name: Creating
       run : write-host "Hello friends created by $NAME"

  my_second_job:
    name: my sec ob
    runs-on: ubuntu-latest
    steps:
     - name: creat_second
       run:  echo "Hello my friend $NAME"
    
       
  
